
services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app
    ports:
      - 6379:6379
    volumes:
      - ./redis-volume:/data
  fastapi:
    build: backend/
    command: uvicorn app:app --host 0.0.0.0 --port 18004
    environment:
      - CUDA_VISIBLE_DEVICES=0
    ports:
      - 18004:18004
    networks:
      - app
  react:
    build: frontend/
    ports:
      - 80:80
    networks:
      - app


networks:
  app:
    driver: bridge
