FROM python:3.8-buster
USER root
RUN apt-get update -y
RUN apt-get install -y python3 python3-pip
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
WORKDIR /app
COPY requirements.txt ./requirements.txt
RUN pip3 install -U pip
RUN pip3 install -r requirements.txt
COPY . .
EXPOSE 18004